name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          # ubuntu - x86
          - os: ubuntu-latest
            architecture: x64
            runner: ubuntu-latest
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        run: cargo test